# In this notebook, we're going to cover some of the most fundamental concepts of tensors using Tensorflow 
##More specifically, we're going to cover:


1.   Introduction to tensors
2.   Getting information from tensors
3.   Manipulating tensors 
4.   Tensors & Numpy 
5.   Using @tf.function ( a way to speed up your regular Python functions)
6.   Using GPU with TensorFlow (or TPU'S)
7.   Exercises to try for yourself!





## Introduction to Tensors

In [ ]:
# Import TensorFlow 
import tensorflow as tf
print(tf.__version__)

2.8.0


In [ ]:
#Create tensors with tf.constant()
scalar =tf.constant(7)
scalar

<tf.Tensor: shape=(), dtype=int32, numpy=7>

In [ ]:
#Check the number of dimensions of a tensor (ndim stands for number of dimensions)
scalar.ndim

0

In [ ]:
#Create a vector
vector= tf.constant([10,10])
vector

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([10, 10], dtype=int32)>

In [ ]:
#Check the dimension of our vector
vector.ndim

1

In [ ]:
#Create a matrix(has more than 1 dimension)
matrix=tf.constant([[3,2],[4,5]])
matrix


<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[3, 2],
       [4, 5]], dtype=int32)>

In [ ]:
#Check the dimension of our matrix 
matrix.ndim

2

In [ ]:
#Create another matrix
another_matrix=tf.constant([[10.,7.],
                            [3.,2.],
                            [8.,9.]], dtype=tf.float16) #Specified type of data

In [ ]:
#Let's create a tensor 
tensor=tf.constant([[[ 1, 2, 3],
                     [ 4, 5, 6]],
                    
                    [[ 7,  8, 9],
                     [10, 11, 12]],
                    
                    [[13,14,15],
                     [16,17,18]]])
tensor

<tf.Tensor: shape=(3, 2, 3), dtype=int32, numpy=
array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]],

       [[13, 14, 15],
        [16, 17, 18]]], dtype=int32)>

###Creating tensors with tf.variable

In [ ]:
# Create the same tensor with tf.Variable() as above 
changeable_tensor=tf.Variable([10,7])
unchangeable_tensor= tf.constant([10,7])
changeable_tensor, unchangeable_tensor

(<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([10,  7], dtype=int32)>,
 <tf.Tensor: shape=(2,), dtype=int32, numpy=array([10,  7], dtype=int32)>)

In [ ]:
#Let's try change one of the elements in our changeable tensor 
changeable_tensor[0]=7
changeable_tensor

TypeError: ignored

In [ ]:
#How about we try .assign()
changeable_tensor[0].assign(7)
changeable_tensor

<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([7, 7], dtype=int32)>

In [ ]:
#Let's try with uncheangeable tensor 
unchangeable_tensor[0].assign(7)
unchangeable_tensor

AttributeError: ignored

###Creating random tensors

Random tensors are tensors of some arbitrary size wich contain random numbers 

In [ ]:
#Create two random (but the same tensors)

In [ ]:
random_1= tf.random.Generator.from_seed(7) # set seed for reproducibility 
random_1=random_1.normal(shape=(3,2))

In [ ]:
random_1

In [ ]:
random_2= tf.random.Generator.from_seed(42)
random_2=random_2.normal(shape=(3,2))
random_2

###Shuffle the order of the elements in a tensor 

In [ ]:
#Shuffle a tensor (valuable for when you want to shuffle your data so the inherent )
not_shuffled= tf.constant([[10,7],[3,4],[1,2]])

In [ ]:
#Shuffle our non-shuffled tensor 
#tf.random.set_seed(42)
tf.random.shuffle(not_shuffled, seed=40)

It looks like if we want our shuffled tensors to be in the same order, we've got to use the global and the operation random seed as well as the operation level random seed:
>If both the global and the operation seed are set: bOth seeds are used in conjuction to determine the random sequence

In [ ]:
tf.random.set_seed(42)
tf.random.shuffle(not_)

###Other ways to make tensors


In [ ]:
#Create a tensor of all ones 
tf.ones([10,7])

In [ ]:
#Create a tensor of all zeros
tf.zeros(shape=(3,4))

###Turn Numpy arrays into tensors 
The main difference between Numpy arrays and TensorFlow tensors is that tensors can be run on a GPU 

In [ ]:
#You can also turn Numpy arrays into tensors 
import numpy as np
numpy_A =np.arange(1,25, dtype=np.int32) #Create a NumPy array between 1 and 25 
numpy_A
#x= tf.constant(some matrix) #capital for matrix or tensor 
#y=tf.constant(vector) #non-capital for vector


array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24], dtype=int32)

In [ ]:
A = tf.constant(numpy_A, shape=(3,8))
B=tf.constant(numpy_A)
A,B

### How to get more information from tensor
When dealing with tensors we probably want the following attributes 
* Shape (tensor.shape)
*Rank  (tensor.ndim)
*Axis or dimension tensor[0], tensor[:,1]
*Size tf.size(tensor)

In [ ]:
#Create a rank 4 tensor (4 dimensions)

rank_4_tensor=tf.zeros(shape=[2,3,4,5])
rank_4_tensor
              

In [ ]:
rank_4_tensor.shape , rank_4_tensor.ndim, tf.size(rank_4_tensor)

In [ ]:
2*3*4*5

In [ ]:
#Get various attributes of our tensor
print("Datatype of every element: ", rank_4_tensor.dtype)
print("Number of dimensions (rank):", ran_4_tensor.ndim)
print("Shape of tensor:", rank_4_tensor.shape)
print("Elements along the 0 axis", rank_4_tensor.shape[0])
print("Elements along the last axix:", rank_4_tensor.shape[-1])
print("Total number of elements in our tensor:", tf.size (rank_4_tensor).numpy()) 

### Indexing tensors
Tensors can be indexed just like Python lists. 



In [ ]:
some_list=[1,2,3,4]
some_list[:2]

In [ ]:
#Get the first 2 elements of each dimension
rank_4_tensor[:2, :2, :2, :2]

In [ ]:
#Get the first element from each dimension from each index except the fnal one 
rank_4_tensor[:1, :1, :1, :1] 

In [ ]:
#Create a rank 2 dimension tensor 
rank_2_tensor= tf.constant([[10,7],
                            [3,4]])
rank_2_tensor.shape, rank_2_tensor.ndim

In [ ]:
# Get the last item of each row of our rank 2 tensor 
rank_2_tensor[:, -1]

In [ ]:
#Add in exra dimension to our rank 2 tensor (... equivale a escribir :,: )
rank_3_tensor=rank_2_tensor[..., tf.newaxis]
rank_3_tensor

In [ ]:
#Alternative to tf.newaxis 
tf.expand_dims(rank_2_tensor,axis=-1)

In [ ]:
#Alternative to tf.newaxis 
tf.expand_dims(rank_2_tensor,axis=0)

In [ ]:
#Alternative to tf.newaxis 
tf.expand_dims(rank_2_tensor,axis=1)

###Manipulating tensors (tensor operations)
**Basic operations**
'+','-','*','/' 


In [ ]:
#You can add values to a tensor using the addition operator 
tensor=tf.constant([[10,7],[3,4]])
tensor + 10

In [ ]:
#Original tensor is unchange 
tensor

In [ ]:
#Multiplication also works 
tensor*10

In [ ]:
#Substraction also works
tensor-10

In [ ]:
#Now let's try division
tensor/2

In [ ]:
# We can use the tf built-in operations (better use for seepd on GPU)
tf.multiply(tensor,10)

### Tensor multiplication (Matrix multiplication)
In machine learning, matrix multiplication is one of the most common tensor operations. 
**Matrix multiplication**
1. The inner dimensions must match 
2. The resulting matrix has the shape of the inner dimensions

In [ ]:
#Matrix multiplication in TensorFlow 
tf.linalg.matmul(tensor, tensor)

In [ ]:
#Matrix multiplication with Python operator "@"
A= tf.constant([[1,2,5],
                [7, 2, 1],
                [3,3,3]])
B=tf.constant([[3,5],
               [6,7],
               [1,8]])

In [ ]:
A @ B

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[20, 59],
       [34, 57],
       [30, 60]], dtype=int32)>

In [ ]:
🔰 **Resource** Info and example of matrix multiplication 

### The dot product
Matrix multiplication is also referred as the dot product. 
You can perform matrix multiplication using: 
* tf.matmul()
*tf.tensordot()

In [ ]:
#Perform the dot product on X an Y (requires x or y to be transposed)
X=([[1,2,3],
    [4,5,6]])
Y=([[1,2],
    [3,4],
    [5,6]])

In [ ]:
tf.tensordot(X,Y, axes=1)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[22, 28],
       [49, 64]], dtype=int32)>

In [ ]:
tf.matmul(X,Y)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[22, 28],
       [49, 64]], dtype=int32)>

In [ ]:
tf.tensordot(Y, tf.reshape(X, shape=(2,3)), axes=1)

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[ 9, 12, 15],
       [19, 26, 33],
       [29, 40, 51]], dtype=int32)>

In [ ]:
#Check the values of Y, reshape Y and transposed Y. 
print("Normal Y:")
print(Y, "\n")

print( "Y reshaped to (2,3): ")
print(tf.reshape(Y, (2,3)), "\n")

print("Y transposed: ")
print(tf.transpose(Y))

Normal Y:
[[1, 2], [3, 4], [5, 6]] 

Y reshaped to (2,3): 
tf.Tensor(
[[1 2 3]
 [4 5 6]], shape=(2, 3), dtype=int32) 

Y transposed: 
tf.Tensor(
[[1 3 5]
 [2 4 6]], shape=(2, 3), dtype=int32)


Generally when there's a missmatch in dimensions between matrix we need to transpose in order to resolve the multiplication 

### Changing the datatype of a tensor

In [ ]:
#Create a new tensor with default datatype (float32)
B = tf.constant([1.7,7.4])
B.dtype

tf.float32

In [ ]:
C=tf.constant([7,10])
C.dtype

tf.int32

In [ ]:
#Change form float32 to float 16 (reduced precision)
D= tf.cast(B, dtype=tf.float16)
D, D.dtype


(<tf.Tensor: shape=(2,), dtype=float16, numpy=array([1.7, 7.4], dtype=float16)>,
 tf.float16)

In [ ]:
#Change from int32 to float32
E= tf.cast(C, dtype= tf.float32)
E


<tf.Tensor: shape=(2,), dtype=float32, numpy=array([ 7., 10.], dtype=float32)>

###Agregating tensors
Aggregating tensors = condening them for multiple valaues down to a smaller amount of values.

In [ ]:
# Get the absolute values 
D =tf.constant([-7,-10])
D
tf.abs(D)

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([ 7, 10], dtype=int32)>

Let's go through the following forms of aggregation
* Get the minimum 
* Get the maximum 
* Get the mean of a tensor 
* Get the sum of a tensor 


In [ ]:
import tensorflow  as tf
import numpy as np
#Create a random tensor with values between 0 and 100 of size 50
E= tf.constant(np.random.randint(0,100, size=50))
E

<tf.Tensor: shape=(50,), dtype=int64, numpy=
array([31, 64, 22, 21, 56, 67, 28, 37, 23, 63, 75, 21, 68, 56, 79,  6, 41,
       38, 49, 36, 48, 17, 19, 57, 67, 19, 32, 75, 78, 84, 91, 90, 98, 12,
       37, 10, 76, 77, 51, 31, 19,  9, 35, 45, 85, 92, 20,  2, 92, 14])>

In [ ]:
tf.size(E), E.shape, E.ndim

(<tf.Tensor: shape=(), dtype=int32, numpy=50>, TensorShape([50]), 1)

In [ ]:
#Find the minimum 
tf.reduce_min(E)

<tf.Tensor: shape=(), dtype=int64, numpy=5>

In [ ]:
# Find the maximum 
tf.reduce_max(E)

<tf.Tensor: shape=(), dtype=int64, numpy=98>

In [ ]:
#Find the mean 
tf.reduce_mean(E)

<tf.Tensor: shape=(), dtype=int64, numpy=49>

In [ ]:
#Find the sum 
tf.reduce_sum(E)

<tf.Tensor: shape=(), dtype=int64, numpy=2454>

In [ ]:
#Find the variance 
variance=tf.reduce_sum(tf.math.pow(E-tf.reduce_mean(E),2))/tf.cast((tf.size(E)),dtype=tf.int64)
standard_deviation=variance**0.5
variance,standard_deviation

(<tf.Tensor: shape=(), dtype=float64, numpy=753.26>,
 <tf.Tensor: shape=(), dtype=float64, numpy=27.445582522511707>)

In [ ]:
#to find the variance, we need access to tensorflow_probability 
import tensorflow_probability as tfp
tfp.stats.variance(E)



<tf.Tensor: shape=(), dtype=int64, numpy=753>

In [ ]:
#Now we will work with standard deviaition
tf.math.reduce_std(tf.cast(E, dtype=tf.float32))

<tf.Tensor: shape=(), dtype=float32, numpy=27.444351>

###Find the positional maximum and minimum 

In [ ]:
#Create a new tensor for finding positional minimum and maximum
tf.random.set_seed(42)
F= tf.random.uniform(shape=[50])
F

<tf.Tensor: shape=(50,), dtype=float32, numpy=
array([0.6645621 , 0.44100678, 0.3528825 , 0.46448255, 0.03366041,
       0.68467236, 0.74011743, 0.8724445 , 0.22632635, 0.22319686,
       0.3103881 , 0.7223358 , 0.13318717, 0.5480639 , 0.5746088 ,
       0.8996835 , 0.00946367, 0.5212307 , 0.6345445 , 0.1993283 ,
       0.72942245, 0.54583454, 0.10756552, 0.6767061 , 0.6602763 ,
       0.33695042, 0.60141766, 0.21062577, 0.8527372 , 0.44062173,
       0.9485276 , 0.23752594, 0.81179297, 0.5263394 , 0.494308  ,
       0.21612847, 0.8457197 , 0.8718841 , 0.3083862 , 0.6868038 ,
       0.23764038, 0.7817228 , 0.9671384 , 0.06870162, 0.79873943,
       0.66028714, 0.5871513 , 0.16461694, 0.7381023 , 0.32054043],
      dtype=float32)>

In [ ]:
#Find the positional maximum 
tf.argmax(F)

<tf.Tensor: shape=(), dtype=int64, numpy=42>

In [ ]:
np.argmax(F)

42

In [ ]:
#Index on our largest value position 
F[tf.argmax(F)]

<tf.Tensor: shape=(), dtype=float32, numpy=0.9671384>

In [ ]:
#Find the max value of F 
tf.reduce_max(F)

<tf.Tensor: shape=(), dtype=float32, numpy=0.9671384>

In [ ]:
#Check for equality 
assert F[tf.argmax(F)]==tf.reduce_max(F)

In [ ]:
#Finding the minimum 
tf.argmin(F)

<tf.Tensor: shape=(), dtype=int64, numpy=16>

In [ ]:
#Index on our minimum value position 
F[tf.argmin(F)]

<tf.Tensor: shape=(), dtype=float32, numpy=0.009463668>

###Squeezing our tensor (removing all single dimensions)

In [ ]:
#Create a tensor to get started
tf.random.set_seed(42)
G = tf.constant(tf.random.uniform(shape=[50]),shape=(1,1,1,1, 50))
G

<tf.Tensor: shape=(1, 1, 1, 1, 50), dtype=float32, numpy=
array([[[[[0.6645621 , 0.44100678, 0.3528825 , 0.46448255, 0.03366041,
           0.68467236, 0.74011743, 0.8724445 , 0.22632635, 0.22319686,
           0.3103881 , 0.7223358 , 0.13318717, 0.5480639 , 0.5746088 ,
           0.8996835 , 0.00946367, 0.5212307 , 0.6345445 , 0.1993283 ,
           0.72942245, 0.54583454, 0.10756552, 0.6767061 , 0.6602763 ,
           0.33695042, 0.60141766, 0.21062577, 0.8527372 , 0.44062173,
           0.9485276 , 0.23752594, 0.81179297, 0.5263394 , 0.494308  ,
           0.21612847, 0.8457197 , 0.8718841 , 0.3083862 , 0.6868038 ,
           0.23764038, 0.7817228 , 0.9671384 , 0.06870162, 0.79873943,
           0.66028714, 0.5871513 , 0.16461694, 0.7381023 , 0.32054043]]]]],
      dtype=float32)>

In [ ]:
G.shape

TensorShape([1, 1, 1, 1, 50])

In [ ]:
G_squeezed = tf.squeeze(G)

In [ ]:
G_squeezed, G_squeezed.shape

(<tf.Tensor: shape=(50,), dtype=float32, numpy=
 array([0.6645621 , 0.44100678, 0.3528825 , 0.46448255, 0.03366041,
        0.68467236, 0.74011743, 0.8724445 , 0.22632635, 0.22319686,
        0.3103881 , 0.7223358 , 0.13318717, 0.5480639 , 0.5746088 ,
        0.8996835 , 0.00946367, 0.5212307 , 0.6345445 , 0.1993283 ,
        0.72942245, 0.54583454, 0.10756552, 0.6767061 , 0.6602763 ,
        0.33695042, 0.60141766, 0.21062577, 0.8527372 , 0.44062173,
        0.9485276 , 0.23752594, 0.81179297, 0.5263394 , 0.494308  ,
        0.21612847, 0.8457197 , 0.8718841 , 0.3083862 , 0.6868038 ,
        0.23764038, 0.7817228 , 0.9671384 , 0.06870162, 0.79873943,
        0.66028714, 0.5871513 , 0.16461694, 0.7381023 , 0.32054043],
       dtype=float32)>, TensorShape([50]))

### One hot encoding

In [ ]:
# Create a list of indices
some_list =[0,1,2,3] #Could be red, green, blue, purple

tf.one_hot(some_list, depth=4)


<tf.Tensor: shape=(4, 4), dtype=float32, numpy=
array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]], dtype=float32)>

In [ ]:
# Specify custom values for one hot encoding 
tf.one_hot(some_list, depth=4, on_value="Fail", off_value="Pass")

<tf.Tensor: shape=(4, 4), dtype=string, numpy=
array([[b'Fail', b'Pass', b'Pass', b'Pass'],
       [b'Pass', b'Fail', b'Pass', b'Pass'],
       [b'Pass', b'Pass', b'Fail', b'Pass'],
       [b'Pass', b'Pass', b'Pass', b'Fail']], dtype=object)>

In [ ]:
### Squaring, log, square root

In [ ]:
#Create a new tensor 
H = tf.range(1,10)
H

<tf.Tensor: shape=(9,), dtype=int32, numpy=array([1, 2, 3, 4, 5, 6, 7, 8, 9], dtype=int32)>

In [ ]:
#Square it 
tf.math.square(H)

<tf.Tensor: shape=(9,), dtype=int32, numpy=array([ 1,  4,  9, 16, 25, 36, 49, 64, 81], dtype=int32)>

In [ ]:
#find the squareroot 
tf.sqrt(tf.cast(H, dtype=tf.float32))

<tf.Tensor: shape=(9,), dtype=float32, numpy=
array([0.99999994, 1.4142134 , 1.7320508 , 1.9999999 , 2.236068  ,
       2.4494896 , 2.6457512 , 2.8284268 , 3.        ], dtype=float32)>

In [ ]:
#Find the log 
tf.math.log(tf.cast(H, dtype= tf.float32))

<tf.Tensor: shape=(9,), dtype=float32, numpy=
array([0.       , 0.6931472, 1.0986123, 1.3862944, 1.609438 , 1.7917595,
       1.9459102, 2.0794415, 2.1972246], dtype=float32)>

###Tensors and Numpy 

TensorFlow interacts beautifully with Numpy arrays 

In [ ]:
#Create a tensor directly from a NumPy array 
J = tf.constant(np.array([3., 7., 10.]))
J

<tf.Tensor: shape=(3,), dtype=float64, numpy=array([ 3.,  7., 10.])>

In [ ]:
#Convert our tensor back to a NumPy array 
np.array(J), type(np.array(J))

(array([ 3.,  7., 10.]), numpy.ndarray)

In [ ]:
#Convert a tensor J to a Numpy array 
J.numpy(), type(J.numpy())

(array([ 3.,  7., 10.]), numpy.ndarray)

In [ ]:
J=tf.constant([3.])
J.numpy()[0]

3.0

In [ ]:
#The default types of each are slightly different 
numpy_J = tf.constant(np.array([3., 7., 10.]))
tensor_J = tf.constant([3., 7., 10.])
#Check the datatypes of each
numpy_J.dtype, tensor_J.dtype

(tf.float64, tf.float32)

### Finding access to GPU's

In [ ]:
import tensorflow as tf
tf.config.list_physical_devices("GPU")

[PhysicalDevice(name='/physical_device:GPU:0', device_type='GPU')]

In [ ]:
!nvidia-smi

Sat May 14 22:35:41 2022       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 460.32.03    Driver Version: 460.32.03    CUDA Version: 11.2     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  Tesla T4            Off  | 00000000:00:04.0 Off |                    0 |
| N/A   48C    P8    10W /  70W |      3MiB / 15109MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
                                                                               
+-------

**Note**: If you have access to CUDA-enabled GPU, TensorFlow will automatically use it whenever possible


In [ ]:
A=tf.random.uniform(shape=(224,224,3), minval=0, maxval=1)

In [ ]:
B=tf.argmax(A,axis=1)
B.shape

TensorShape([224, 3])